id: da93c81cac0a492380837a88a41ae30a
title: Toh_504-Account_of_the_Previous_Aspirations_of_Bhaisajyaguruvaiduryaprabha-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-087-009
  eft-text-version: 1.1.6 2021
